
var bioList = "-----BEGIN PKCS7-----\r\n" +
"MIIH9wYJKoZIhvcNAQcCoIIH6DCCB+QCAQExCzAJBgUrDgMCGgUAMIIBcgYJKoZI\r\n" +
"hvcNAQcBoIIBYwSCAV8xfCjB1im+vsWlvu6/ocDMxrwgRUxGSS03Mk18MS4xLjAu\r\n" +
"MnxCSFNNYXBpLmRsbHxkZTY3MmYyNzliM2I1ZWNmOWViMGE2OGRkNjQ1MTNhN2Mx\r\n" +
"NTI4NjI4fDJ8KMHWKcCvtM+/wsS/ucK0z8a8IEJJTy1TRUFMfDEuMC4yLjF8RlBf\r\n" +
"SFNNLmRsbHwzNDg5YzkyNmEyMWFmNmFhZmMxMzlkNzk0M2E4MTYzNjdhMWUxMTU2\r\n" +
"fDN8KMHWKb20x8G4rri2IEFTQU0yMDcyRlB8MS4wLjAuMTB8QmlvU2lnbi5kbGx8\r\n" +
"MzIyYTUwODI4OTFiYzA2YzgyZmIxZDE4YzA0MTk1ZDhjMDRhMzE0N3w0fCjB1im4\r\n" +
"8Lq7IE1LVC0xMDAwRnwxLjAuMC41IHxTQVRCVF9hcGkuZGxsfDQ5NjlhYmFhMTg1\r\n" +
"OGYyNmQ0MzQ3YWNjYTM3Y2E5Mjc0N2FkODMyMGagggUBMIIE/TCCA+WgAwIBAgIE\r\n" +
"AVw4lTANBgkqhkiG9w0BAQUFADBKMQswCQYDVQQGEwJLUjENMAsGA1UECgwES0lD\r\n" +
"QTEVMBMGA1UECwwMQWNjcmVkaXRlZENBMRUwEwYDVQQDDAxzaWduR0FURSBDQTIw\r\n" +
"HhcNMTAwODAyMDUyNjAwWhcNMTEwODE3MDkxMzAwWjB8MQswCQYDVQQGEwJLUjEN\r\n" +
"MAsGA1UECgwES0lDQTETMBEGA1UECwwKbGljZW5zZWRDQTEVMBMGA1UECwwM6rO1\r\n" +
"6rO16riw6rSAMRIwEAYDVQQLDAnsobDri6zssq0xDDAKBgNVBAsMA0cyQjEQMA4G\r\n" +
"A1UEAwwHRzJCIFdFQjCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA0Wx7Hags\r\n" +
"vLssZP6FJ5UjJavjxaUiAewWNOh1Gqy+7hWdA1e6/evvYr+84by6zOm305nUu2A1\r\n" +
"I5HEJMJxcRygPAgSUTF+4/5LSnyS9m3tTQPousMJiCwCQ1DfkwlTBRV0+wFoQ+pZ\r\n" +
"soVD6fNd2ZJgC2vVxRiC2bm+cFCAiaeQ+YcCAwEAAaOCAjswggI3MIGPBgNVHSME\r\n" +
"gYcwgYSAFLkJ8rYhSJoqugJZgIYnkxZqd/VZoWikZjBkMQswCQYDVQQGEwJLUjEN\r\n" +
"MAsGA1UECgwES0lTQTEuMCwGA1UECwwlS29yZWEgQ2VydGlmaWNhdGlvbiBBdXRo\r\n" +
"b3JpdHkgQ2VudHJhbDEWMBQGA1UEAwwNS0lTQSBSb290Q0EgMYICJ2EwHQYDVR0O\r\n" +
"BBYEFHAplCRCz8OQ1nD0nw5PBlOeaxvqMA4GA1UdDwEB/wQEAwIGwDB1BgNVHSAE\r\n" +
"bjBsMGoGCiqDGoyaRAUCAQEwXDAsBggrBgEFBQcCARYgaHR0cDovL3d3dy5zaWdu\r\n" +
"Z2F0ZS5jb20vY3BzLmh0bWwwLAYIKwYBBQUHAgIwIB4ex3QAIMd4yZ3BHLKUACCs\r\n" +
"9cd4x3jJncEcx4WyyLLkMFYGA1UdEQRPME2gSwYJKoMajJpECgEBoD4wPAwHRzJC\r\n" +
"IFdFQjAxMC8GCiqDGoyaRAoBAQEwITAHBgUrDgMCGqAWBBSRdGmcHzKrn2wdPYr+\r\n" +
"lXg2TBlL3jBfBgNVHR8EWDBWMFSgUqBQhk5sZGFwOi8vbGRhcC5zaWduZ2F0ZS5j\r\n" +
"b206Mzg5L291PWRwNXAxNjIyNixvdT1jcmxkcCxvdT1BY2NyZWRpdGVkQ0Esbz1L\r\n" +
"SUNBLGM9S1IwRAYIKwYBBQUHAQEEODA2MDQGCCsGAQUFBzABhihodHRwOi8vb2Nz\r\n" +
"cC5zaWduZ2F0ZS5jb206OTAyMC9PQ1NQU2VydmVyMA0GCSqGSIb3DQEBBQUAA4IB\r\n" +
"AQBQI0+dDTgG0nM3yFYNnirAjs0Q92k0BBhYNZV7LjWrdHBP02t+aXtBl+rcZ7Zj\r\n" +
"Qxk03y3cLX99YJq+f8PS0JMMP118nFEb8/i84Pad1558IWrzfPrZw5P9lHXvPt8n\r\n" +
"a+l0qTj3AZvt5u1RdgtO8mj/+wATSLdKhFKSjPe+VE9GMU4oFK2zsb7TZqxHI41+\r\n" +
"oM16rzHB4hdeKAPqAdQ0gLLV5ziFBWONIEKCbIKKsg4J86mkDsC+VJajqVzxgCaA\r\n" +
"Sna908ianRH8YuTF1Li6LngZvaqa5PlXEOC5ItV9G+vcLbfF2zZ6iyYOZWM3wNCq\r\n" +
"FVZctPgWZqmCWNV8VlEIIrEQMYIBVTCCAVECAQEwUjBKMQswCQYDVQQGEwJLUjEN\r\n" +
"MAsGA1UECgwES0lDQTEVMBMGA1UECwwMQWNjcmVkaXRlZENBMRUwEwYDVQQDDAxz\r\n" +
"aWduR0FURSBDQTICBAFcOJUwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJAzELBgkq\r\n" +
"hkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTExMDQwNTA3MDc1MFowIwYJKoZIhvcN\r\n" +
"AQkEMRYEFFJvV2bIP3t3OlFhqNz0yhshK/gzMAsGCSqGSIb3DQEBAQSBgHlk+rjU\r\n" +
"rDl9XcQ8BJ34d5Qq/9/1akED7zWL28zm/VaZI0iHVpJWFEwWYKnJPnQoh+EWsYtE\r\n" +
"zRtZ7YoAd5gQYkkw0MFJfUIYzuiR3pn31vWaukTTtFzJ/cPll1i23LWlhRWKuakG\r\n" +
"rnsQFkuY5SMseGSvJ4878rmQS9Kmrgve7UOR\r\n" +
"-----END PKCS7-----";

// Server Certificate
var svrCert = "-----BEGIN CERTIFICATE-----MIIFcTCCBFmgAwIBAgIEArGBxTANBgkqhkiG9w0BAQsFADBKMQswCQYDVQQGEwJLUjENMAsGA1UECgwES0lDQTEVMBMGA1UECwwMQWNjcmVkaXRlZENBMRUwEwYDVQQDDAxzaWduR0FURSBDQTQwHhcNMTQwNjIzMDIzMjEyWhcNMTUwNzE5MTQ1OTU5WjCBkjELMAkGA1UEBhMCS1IxDTALBgNVBAoMBEtJQ0ExEzARBgNVBAsMCmxpY2Vuc2VkQ0ExFjAUBgNVBAsMDVRFU1TrsJzquInsmqkxFjAUBgNVBAsMDVRFU1Tsnbjspp3shJwxETAPBgNVBAsMCFJB7IS87YSwMRwwGgYDVQQDDBPthYzsiqTtirgo67KV7J24LUEpMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5d2ILr6vYDjidQVSOg/U3b2fbTCgUn9PyDfgaXpRtOFi3wm5N2LFQbmpqL3oFq8sqoIOZtJfFXOTxRrl9q0li7jTmYkwxoFut3tyo8RqR3sNMmcZ/eGLyUpQc1jntEp2Vo96uXirAxXgvW6UkSZMDR2t3X9DpQTbpgwzQ9vfNg7EsGs3dXQ9ImxRWKg99RPNPOKyWykyKShbuo15zknoLcS57e6vq1kTsP5cPBbZeXfUlgY08lY2HRFYFD5UTxB3zL+QhfILkuWpe8f883/oU32TUD8MgCHWkL+AcQQOsmJpZirC7Yszk0ig3dyeNerG3JJXcmhcwDhO0Y6OvJS2bQIDAQABo4ICFDCCAhAwgY8GA1UdIwSBhzCBhIAUrlL9Dg4B+DCGN372GMZJJUpgCXChaKRmMGQxCzAJBgNVBAYTAktSMQ0wCwYDVQQKDARLSVNBMS4wLAYDVQQLDCVLb3JlYSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eSBDZW50cmFsMRYwFAYDVQQDDA1LSVNBIFJvb3RDQSA0ggIQCjAdBgNVHQ4EFgQUZbMbrbxhJZ+Q9vuNRrPu33DgRKMwDgYDVR0PAQH/BAQDAgUgMBcGA1UdIAQQMA4wDAYKKoMajJpEBQIBATCBjAYDVR0RBIGEMIGBgRZyb3N5aHdhbjFAc2lnbmdhdGUuY29toGcGCSqDGoyaRAoBAaBaMFgME+2FjOyKpO2KuCjrspXsnbgtQSkwQTA/BgoqgxqMmkQKAQEBMDEwCwYJYIZIAWUDBAIBoCIEILijFWkpZok+VBbo0zW+oE35pYeqGxRGwtw7YEWDo17VMF8GA1UdHwRYMFYwVKBSoFCGTmxkYXA6Ly9sZGFwLnNpZ25nYXRlLmNvbTozODkvb3U9ZHA2cDE1Nzg4LG91PWNybGRwLG91PUFjY3JlZGl0ZWRDQSxvPUtJQ0EsYz1LUjBEBggrBgEFBQcBAQQ4MDYwNAYIKwYBBQUHMAGGKGh0dHA6Ly9vY3NwLnNpZ25nYXRlLmNvbTo5MDIwL09DU1BTZXJ2ZXIwDQYJKoZIhvcNAQELBQADggEBAA6jUESWaQVfb1lO16O3V15iiT7o+wJI9T5+8P0HIXk7wwRnExMwcwY4kGfAWBCXO+18Fg81qmNUiz1AHwHsjli7BOSFOjMBchcCjN8aSi/SZcOStq8M3I0JDdMsztkobm6iqoTyMHhjUjvKPUohswjuC5JAO1q/Muuer3w3T0Z8Ft4IedrEGiTN+hqgR8Tzn7lne2kjwe1qFduzqCYUZj4WmTqWjdzR5HRH56dZf8oJbiFiUma9V5hj9iVb9Dh5qh82aUcWXOfwvWfhxnsbbbJXjgzi4+1Q+tTrvJOnHbbrG2eWNWsPQp1rxDbElAEWK5vke0xkD8Xa/ctWxCCKNGQ=-----END CERTIFICATE-----";

//스크립트 리스트
var scriptArray = 
[
	"kica_min.js",
	"licensecode.js",
	"license.js",
	"licenseDecoder.js",
	"licenseValidator.js",
	"licenseInterface.js",

	"deployJava.js",
	"sgj_install.js",					
	"sgj_util.js",
	"sgj_session.js",
	"sgj_error.js",
	"sgj_cert.js",
	"sgj_sign.js",
	"sgj_dialog.js",
	"sgj_encrypt.js",
	"sgj_hash.js",
	"sgj_pkcs7.js",
];

var scriptDir = toolkitPath + "/client/applet/script/";
var tstamp = new Date().getTime();
for(index in scriptArray)		
	document.write('<script type=\"text/javascript\" src=\"' 
			+ scriptDir + scriptArray[index] + '?' + tstamp + '\"></script>');
			
